import { h, render, Component } from 'preact'
import Header from 'UiKit/Header/index'

import {get_convo_html, get_sentencesss_html, force_rerender} from 'render'
import state from 'state'
import * as dom from 'dom'
import {convo, reset_convo, restart_sentence, update_conversation} from 'convo'
import {remove_sentence} from 'model'

import Button from 'UiKit/Button/'
import './styles.css'

let consent_no = false
function logout() {
  window.location.reload()

  // the below should work, but there's some kind of state maintained in Preact so just redo the whole thing instead
  state.email = null
  reset_convo()
  force_rerender()
}

function remove(id) {
  // FIXME: this is called from html generated by render.js and only works because of a side-effect of rollup -- it's really gnarly so plz fixie svp!
  if(id === -1) return false

  let ids = convo.sentences[id].ids
  remove_sentence(ids)
  convo.sentences.splice(id, 1)
  force_rerender()
}

remove(-1)

const Story = () => {

  function add_consent(param) {
    return function() {
      if(param) {
        consent_no = false // total hack
        return force_rerender(update_conversation({consent: param}))
      }

      consent_no = true
      force_rerender()
    }
  }

  const thanks =
  <div>
    <div>Thanks for adding to your story! Your latest sentence is highlighted here and on the map.</div>
    <div>
      When you're done you can <button onClick={logout}>end this story</button>
    </div>
  </div>

  const back_button =
  <p onClick={restart_sentence} style={{textAlign: 'left', flex: 'inherit'}}>
    <i class="fa fa-chevron-left pl_1" aria-hidden="true"></i>
    &nbsp;
    Start Over
  </p>

  const footer_buttons =
  <Button type="submit" buttonStyle="next">
    {convo.current.filled.length && back_button || ''}
    Next
    <i class="fa fa-chevron-right pl_1" aria-hidden="true"></i>
  </Button>

  const consent_list =
  <div>
    <div>- That you're consenting to being named in a story on the MozFest Ripple Map, and that MozFest attendees and organizers will be able to read that story</div>
    <div>- That there are risks we will do our best to protect you from: unintentional data usage, monitoring, and surveillance</div>
    <div>- That at any time, you can change your story or mark it for removal.</div>
  </div>

  const consent_buttons =
  <div>
    <div>Do you have the consent of everyone in this story?</div>
    <div class="choice org" onClick={add_consent('me')}>Yes, I’m the only one in this story</div>
    <div class="choice org" onClick={add_consent('verbal')}>Yes, verbal</div>
    <div class="choice org" onClick={add_consent('written')}>Yes, written</div>
    <div class="choice event" onClick={add_consent()}>No/not sure</div>
  </div>

  const consent_disclaimer =
  <div class="padded">
    <div>To add this story we need the consent of everyone in it. To obtain someone’s informed consent tell them the following:</div>
    {consent_list}

    {consent_buttons}
  </div>


  const how_to_consent =
  <div>
    <h4>Ask</h4>
    <p>If you're not sure you have someone’s consent to add them to the Ripple Map, please ask them and provide the following information. You can print out or email this to yourself.</p>

    <h4>Print/Email Consent Info</h4>
    <p>Hi friend, I'd like to add a story about us meeting/collaborating/??? to the MozFest Ripple Map. The Ripple Map is a web application that visualizes stories about a program or event's "ripple effect" — how the immediate outcomes of new learnings or connections give way to long term and large scale impacts.</p>

    <p>Before you give me your consent, here’s what you need to know:</p>

    {consent_list}

    <p>Do I have your consent to name you in this story?</p>

    {consent_buttons}
  </div>

  const current_story =
  <div id="current_story">
    <Header>Your story so far</Header>
    {!convo.current.filled.length && convo.sentences.length && thanks}

    <div dangerouslySetInnerHTML={{__html: get_sentencesss_html()}}></div>
  </div>

  const storytime = <div id="storytime">
    <form id="the-conversation" onSubmit={dom.submit_convo}>
      <div dangerouslySetInnerHTML={{__html: get_convo_html()}}></div>

      {consent_no ? how_to_consent : ''}

      {convo.current.slots.length === 1 && !consent_no && consent_disclaimer}

      {convo.current.slots.length !== 1 && footer_buttons}

      {convo.sentences.length ? current_story : ''}
    </form>
  </div>


  const signup =
  <div id="signup">
    <form id="login" onSubmit={dom.login} class="Story__form">

      <p>We'd love to hear your stories! Let's start with your contact info:</p>
      <input name="email" id="email" type="text" placeholder="email" class="typeahead Story__input" />

      <p>Your name</p>
      <input name="name" id="name" type="text" placeholder="name" class="typeahead Story__input" />

      <p>How are you involved in Mozfest 2017?</p>
      <select name="mz_involved" id="mz_involved" class="Story__input">
        <option value="attended">attendee</option>
        <option value="wrangled at">wrangler</option>
        <option value="presented at">presenter</option>
      </select>

      <p>It’s really important to us that we have your informed consent to add your story to the map. Here’s what you need to know.</p>

      {consent_list}

      <p>Does this all sound okay to you?</p>

      <Button type="submit" buttonStyle="next">Next
        <i class="fa fa-chevron-right pl_1" aria-hidden="true"></i>
      </Button>
    </form>
  </div>



  return (
    <div class="Story">
      <Header>Tell us {convo.sentences.length ? 'more' : ''} about {!convo.sentences.length ? 'your involvement in' : ''} MozFest</Header>
      {state.email ? storytime : signup}
    </div>
  )
}

export default Story
